-- AI Tasks catalog — batch 001 (50 mixed tasks, hand-verified answer keys).
-- Inserts published tasks + answer keys atomically. Safe to re-run only if
-- you want duplicates — it does NOT dedupe.
DO $$
DECLARE
  t jsonb;
  new_id uuid;
  i int := 0;
BEGIN
FOR t IN SELECT * FROM jsonb_array_elements($json$[
{"kind":"microtask","category":"sentiment_analysis","title":"Rate this review's sentiment","difficulty":"easy","reward_cents":2,"xp":3,"est_seconds":15,"content":{"question":"\"The tutorial was clear and I finished my first project the same day!\" — What is the sentiment?","options":["Positive","Negative","Mixed","Neutral"]},"answer":{"choice":0}},
{"kind":"microtask","category":"sentiment_analysis","title":"Rate this review's sentiment","difficulty":"easy","reward_cents":2,"xp":3,"est_seconds":15,"content":{"question":"\"App keeps crashing every time I open my wallet.\" — What is the sentiment?","options":["Positive","Negative","Mixed","Neutral"]},"answer":{"choice":1}},
{"kind":"microtask","category":"sentiment_analysis","title":"Rate this review's sentiment","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":20,"content":{"question":"\"Great content, though the app drains my battery fast.\" — What is the sentiment?","options":["Positive","Negative","Mixed","Neutral"]},"answer":{"choice":2}},
{"kind":"microtask","category":"sentiment_analysis","title":"Rate this statement's sentiment","difficulty":"easy","reward_cents":2,"xp":3,"est_seconds":15,"content":{"question":"\"The package arrived on Tuesday.\" — What is the sentiment?","options":["Positive","Negative","Mixed","Neutral"]},"answer":{"choice":3}},
{"kind":"microtask","category":"sentiment_analysis","title":"Detect the sarcasm","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":25,"content":{"question":"\"Oh great, another update that deletes my progress. Fantastic.\" — What is the real sentiment?","options":["Negative","Positive","Neutral","Mixed"]},"answer":{"choice":0}},
{"kind":"microtask","category":"text_classification","title":"Classify this message","difficulty":"easy","reward_cents":2,"xp":3,"est_seconds":15,"content":{"question":"\"Flash sale! 50% off all courses this weekend only.\" — Category?","options":["Marketing","Delivery update","Personal","Security alert"]},"answer":{"choice":0}},
{"kind":"microtask","category":"text_classification","title":"Classify this message","difficulty":"easy","reward_cents":2,"xp":3,"est_seconds":15,"content":{"question":"\"Your OTP code is 493202. Do not share it with anyone.\" — Category?","options":["Security / verification","Marketing","Personal","News"]},"answer":{"choice":0}},
{"kind":"microtask","category":"text_classification","title":"Classify this message","difficulty":"medium","reward_cents":3,"xp":4,"est_seconds":15,"content":{"question":"\"Hi mum, I'll call you after work.\" — Category?","options":["Personal","Work","Marketing","Delivery update"]},"answer":{"choice":0}},
{"kind":"microtask","category":"text_classification","title":"Classify this message","difficulty":"easy","reward_cents":2,"xp":3,"est_seconds":15,"content":{"question":"\"Rider is 5 minutes away with your order.\" — Category?","options":["Delivery update","Phishing","Marketing","Personal"]},"answer":{"choice":0}},
{"kind":"microtask","category":"text_classification","title":"Spot the phishing message","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":25,"content":{"question":"\"URGENT: Your account will be closed unless you verify now at http://bit.ly/x7z\" — Category?","options":["Phishing / scam","Official bank notice","Marketing","Delivery update"]},"answer":{"choice":0}},
{"kind":"microtask","category":"intent_classification","title":"Classify the user's intent","difficulty":"easy","reward_cents":2,"xp":3,"est_seconds":15,"content":{"question":"\"How do I reset my password?\" — What does the user want?","options":["Account help","Buy a product","Cancel an order","Leave a review"]},"answer":{"choice":0}},
{"kind":"microtask","category":"intent_classification","title":"Classify the user's intent","difficulty":"easy","reward_cents":2,"xp":3,"est_seconds":15,"content":{"question":"\"I want my money back for this order.\" — What does the user want?","options":["Request a refund","Track a delivery","Praise the product","Change address"]},"answer":{"choice":0}},
{"kind":"microtask","category":"intent_classification","title":"Classify the user's intent","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":20,"content":{"question":"\"Does the premium plan include offline mode?\" — What does the user want?","options":["Ask about features","Cancel subscription","Report a bug","Request a refund"]},"answer":{"choice":0}},
{"kind":"microtask","category":"intent_classification","title":"Classify the user's intent","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":20,"content":{"question":"\"The app charged me twice for the same course.\" — What does the user want?","options":["Report a billing problem","Buy another course","Ask about features","Delete account"]},"answer":{"choice":0}},
{"kind":"microtask","category":"response_rating","title":"Rate the AI response","difficulty":"easy","reward_cents":3,"xp":4,"est_seconds":25,"content":{"question":"User: \"Kenya uses EAT (UTC+3). If it is 09:00 UTC, what time is it in Nairobi?\" AI: \"12:00 noon.\" — Is the AI correct?","options":["Correct","Incorrect"]},"answer":{"choice":0}},
{"kind":"microtask","category":"response_rating","title":"Check the AI summary","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":35,"content":{"question":"Original: \"The workshop moved from Hall A to Hall C and now starts at 2pm instead of 10am.\" AI summary: \"Workshop: Hall C, 2pm.\" — Is the summary faithful?","options":["Yes — captures both changes","No — it misses information"]},"answer":{"choice":0}},
{"kind":"microtask","category":"response_rating","title":"Pick the safer AI reply","difficulty":"hard","reward_cents":7,"xp":8,"est_seconds":40,"min_task_level":2,"content":{"question":"User asks an AI for exact medicine dosage. Which reply is better?","options":["A: Gives general info and advises consulting a pharmacist or doctor","B: Confidently prescribes an exact dosage without knowing the patient"]},"answer":{"choice":0}},
{"kind":"microtask","category":"chatbot_evaluation","title":"Rate the chatbot reply","difficulty":"easy","reward_cents":2,"xp":3,"est_seconds":20,"content":{"question":"User: \"My order is late.\" Bot: \"That's your problem, not mine.\" — Is this reply acceptable?","options":["No — rude and unhelpful","Yes — it is honest"]},"answer":{"choice":0}},
{"kind":"microtask","category":"chatbot_evaluation","title":"Rate the chatbot reply","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":25,"content":{"question":"User: \"Cancel my subscription.\" Bot: \"Done! It's cancelled and a confirmation email is on the way.\" — Is this acceptable?","options":["Acceptable — resolves the request","Unacceptable — ignores the request"]},"answer":{"choice":0}},
{"kind":"microtask","category":"chatbot_evaluation","title":"Spot the factual error","difficulty":"hard","reward_cents":7,"xp":8,"est_seconds":35,"min_task_level":2,"content":{"question":"User: \"What is 15% of 200?\" Bot: \"15% of 200 is 40.\" — Evaluate the reply.","options":["Contains a factual error (correct answer is 30)","The reply is correct"]},"answer":{"choice":0}},
{"kind":"microtask","category":"prompt_evaluation","title":"Pick the better prompt","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":35,"content":{"question":"Goal: get a useful study plan from an AI. Which prompt works better?","options":["A: \"Make me a 2-week study plan for basic Excel, 1 hour per day, beginner level\"","B: \"Teach me computers\""]},"answer":{"choice":0}},
{"kind":"microtask","category":"prompt_evaluation","title":"Pick the better prompt","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":35,"content":{"question":"Goal: translate a business email politely. Which prompt works better?","options":["A: \"Translate this email to French, keep a formal business tone: …\"","B: \"French this: …\""]},"answer":{"choice":0}},
{"kind":"microtask","category":"prompt_evaluation","title":"Improve the vague prompt","difficulty":"hard","reward_cents":7,"xp":8,"est_seconds":40,"min_task_level":2,"content":{"question":"Prompt: \"Write something about business.\" Which single change improves the result MOST?","options":["Specify topic, audience and length (e.g. 200-word intro on M-Pesa for students)","Add the word please","Write it in capital letters","Ask twice"]},"answer":{"choice":0}},
{"kind":"microtask","category":"ocr_correction","title":"Fix the OCR error","difficulty":"easy","reward_cents":2,"xp":3,"est_seconds":20,"content":{"question":"Scanned text: \"Rece1pt t0tal: $45.0O\" — What is the correct text?","options":["Receipt total: $45.00","Recipe total: $45.00","Receipt total: $45.09"]},"answer":{"choice":0}},
{"kind":"microtask","category":"ocr_correction","title":"Fix the OCR error","difficulty":"easy","reward_cents":2,"xp":3,"est_seconds":20,"content":{"question":"Scanned text: \"We1come to the c0urse\" — What is the correct text?","options":["Welcome to the course","Welcome to the curse","Wellcome to the course"]},"answer":{"choice":0}},
{"kind":"microtask","category":"ocr_correction","title":"Fix the OCR error","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":25,"content":{"question":"Scanned text: \"lnvoice #2Ol4 — Due: 3O June\" — What is the correct text?","options":["Invoice #2014 — Due: 30 June","Invoice #2074 — Due: 36 June","Lnvoice #2014 — Due: 30 June"]},"answer":{"choice":0}},
{"kind":"microtask","category":"translation_validation","title":"Validate this Swahili translation","difficulty":"easy","reward_cents":2,"xp":3,"est_seconds":15,"content":{"question":"\"Asante sana\" → \"Thank you very much\" — Is the translation correct?","options":["Correct","Incorrect"]},"answer":{"choice":0}},
{"kind":"microtask","category":"translation_validation","title":"Validate this Swahili translation","difficulty":"easy","reward_cents":2,"xp":3,"est_seconds":15,"content":{"question":"\"Habari za asubuhi\" → \"Good night\" — Is the translation correct?","options":["Incorrect — it means good morning","Correct"]},"answer":{"choice":0}},
{"kind":"microtask","category":"translation_validation","title":"Validate this Spanish translation","difficulty":"medium","reward_cents":3,"xp":4,"est_seconds":20,"content":{"question":"\"¿Cuánto cuesta?\" → \"How much does it cost?\" — Is the translation correct?","options":["Correct","Incorrect"]},"answer":{"choice":0}},
{"kind":"microtask","category":"translation_validation","title":"Validate this French translation","difficulty":"medium","reward_cents":3,"xp":4,"est_seconds":20,"content":{"question":"\"Je suis fatigué\" → \"I am hungry\" — Is the translation correct?","options":["Incorrect — it means I am tired","Correct"]},"answer":{"choice":0}},
{"kind":"annotation","category":"image_labeling","title":"Identify the animal","difficulty":"easy","reward_cents":3,"xp":4,"est_seconds":12,"content":{"question":"Which animal is shown? 🦁","options":["Lion","Tiger","Leopard","Cheetah"]},"answer":{"choice":0}},
{"kind":"annotation","category":"image_labeling","title":"Identify the vehicle","difficulty":"easy","reward_cents":3,"xp":4,"est_seconds":12,"content":{"question":"Which vehicle is shown? 🚁","options":["Helicopter","Airplane","Drone","Hot-air balloon"]},"answer":{"choice":0}},
{"kind":"annotation","category":"image_labeling","title":"Identify the fruit","difficulty":"easy","reward_cents":3,"xp":4,"est_seconds":12,"content":{"question":"Which fruit is shown? 🍍","options":["Pineapple","Mango","Jackfruit","Papaya"]},"answer":{"choice":0}},
{"kind":"annotation","category":"image_labeling","title":"Identify the fruit","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":15,"content":{"question":"Which fruit is shown? 🥭","options":["Mango","Peach","Apricot","Orange"]},"answer":{"choice":0}},
{"kind":"annotation","category":"object_detection","title":"Count the cows","difficulty":"easy","reward_cents":3,"xp":4,"est_seconds":15,"content":{"question":"🐄🐄🐐🐄 — How many cows are in the image?","options":["3","4","2","1"]},"answer":{"choice":0}},
{"kind":"annotation","category":"object_detection","title":"Count the cars","difficulty":"medium","reward_cents":5,"xp":6,"est_seconds":20,"content":{"question":"🚗🚕🚙🚌🏍️ — How many are cars (not bus or motorbike)?","options":["3","4","5","2"]},"answer":{"choice":0}},
{"kind":"annotation","category":"object_detection","title":"Count the fish","difficulty":"medium","reward_cents":5,"xp":6,"est_seconds":20,"content":{"question":"🐟🐟🦀🐟🐙 — How many fish are in the image?","options":["3","4","5","2"]},"answer":{"choice":0}},
{"kind":"annotation","category":"emotion_labeling","title":"Label the emotion","difficulty":"easy","reward_cents":3,"xp":4,"est_seconds":20,"content":{"question":"\"I got the scholarship!!! I can't stop smiling 😭❤️\" — Which emotion fits best?","options":["Joy","Excitement","Anger","Fear"]},"answer":{"accepted":[{"choice":0},{"choice":1}]}},
{"kind":"annotation","category":"emotion_labeling","title":"Label the emotion","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":25,"content":{"question":"\"Why does this always happen to me right before a deadline?!\" — Which emotion fits best?","options":["Frustration","Anger","Joy","Calm"]},"answer":{"accepted":[{"choice":0},{"choice":1}]}},
{"kind":"annotation","category":"emotion_labeling","title":"Label the emotion","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":25,"content":{"question":"\"Honestly I didn't expect the refund to arrive this fast. Wow.\" — Which emotion fits best?","options":["Surprise","Gratitude","Anger","Fear"]},"answer":{"accepted":[{"choice":0},{"choice":1}]}},
{"kind":"annotation","category":"entity_recognition","title":"Find the company","difficulty":"easy","reward_cents":3,"xp":4,"est_seconds":20,"content":{"question":"\"Safaricom launched a new data plan in Mombasa last Friday.\" — Which word is a COMPANY?","options":["Safaricom","Mombasa","Friday","plan"]},"answer":{"choice":0}},
{"kind":"annotation","category":"entity_recognition","title":"Find the airline","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":25,"content":{"question":"\"Fatima booked a flight from Doha to Nairobi with Qatar Airways.\" — Which is an AIRLINE?","options":["Qatar Airways","Fatima","Doha","Nairobi"]},"answer":{"choice":0}},
{"kind":"annotation","category":"entity_recognition","title":"Find the place","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":25,"content":{"question":"\"Amina paid 500 shillings in Nakuru on Monday.\" — Which word is a PLACE?","options":["Nakuru","Amina","Monday","shillings"]},"answer":{"choice":0}},
{"kind":"annotation","category":"document_classification","title":"Categorize the document","difficulty":"easy","reward_cents":3,"xp":4,"est_seconds":20,"content":{"question":"\"CURRICULUM VITAE — Jane Doe. 5 years experience in data entry…\" — Document type?","options":["Resume / CV","Invoice","Contract","News article"]},"answer":{"choice":0}},
{"kind":"annotation","category":"document_classification","title":"Categorize the document","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":25,"content":{"question":"\"This agreement is made between the Landlord and the Tenant for the property at…\" — Document type?","options":["Lease / contract","Receipt","Resume","Report card"]},"answer":{"choice":0}},
{"kind":"annotation","category":"document_classification","title":"Categorize the document","difficulty":"medium","reward_cents":4,"xp":5,"est_seconds":25,"content":{"question":"\"Symptoms: headache, mild fever. Prescribed: paracetamol 500mg, twice daily.\" — Document type?","options":["Medical record","Invoice","Recipe","CV"]},"answer":{"choice":0}},
{"kind":"survey","category":"survey","title":"Task preferences survey","description":"4 quick questions — help us pick the right tasks for you.","difficulty":"easy","reward_cents":10,"xp":10,"est_seconds":90,"content":{"questions":[{"q":"Which tasks do you enjoy most?","options":["Captchas","Image labeling","Surveys","AI rating"]},{"q":"How long is your typical session?","options":["Under 10 min","10–30 min","30–60 min","1 hour+"]},{"q":"When do you usually do tasks?","options":["Morning","Afternoon","Evening","Late night"]},{"q":"What would make you do more tasks?","options":["Higher rewards","More variety","Faster tasks","Bonuses"]}]}},
{"kind":"survey","category":"survey","title":"Learning & earning habits","description":"5 questions about how you combine learning and earning.","difficulty":"easy","reward_cents":12,"xp":10,"est_seconds":120,"content":{"questions":[{"q":"How many courses have you finished here?","options":["None yet","1–2","3–5","6+"]},{"q":"What is your main goal in the app?","options":["Earn money","Learn AI skills","Both equally","Get certified"]},{"q":"How did you find this app?","options":["Friend / referral","Play Store search","Social media","Other"]},{"q":"Do you do online work elsewhere?","options":["Yes, regularly","Sometimes","No, this is my first"]},{"q":"Would you recommend the app to a friend?","options":["Definitely","Maybe","Not yet"]}]}},
{"kind":"survey","category":"survey","title":"App experience survey","description":"4 questions to improve the app.","difficulty":"easy","reward_cents":10,"xp":10,"est_seconds":90,"content":{"questions":[{"q":"How smooth does the app feel?","options":["Very smooth","Okay","Sometimes slow","Often slow"]},{"q":"How fair are the ad breaks?","options":["Fair","Acceptable","Too many"]},{"q":"Which section do you open first?","options":["AI Tasks","Courses","Home","Profile"]},{"q":"What should we build next?","options":["More task types","Withdrawals","More courses","Team challenges"]}]}},
{"kind":"survey","category":"survey","title":"Payout preferences","description":"4 questions about how you want to get paid.","difficulty":"easy","reward_cents":15,"xp":12,"est_seconds":90,"min_task_level":2,"content":{"questions":[{"q":"Preferred payout method?","options":["M-Pesa","PayPal","Bank transfer","Airtime"]},{"q":"Preferred minimum payout?","options":["$1","$5","$10","$20"]},{"q":"How often would you withdraw?","options":["Daily","Weekly","Monthly","When I hit a goal"]},{"q":"Would you swap earnings for premium app features?","options":["Yes","No","Depends on the deal"]}]}}
]$json$::jsonb)
LOOP
  i := i + 1;
  INSERT INTO ai_tasks (kind, category, title, description, difficulty, reward_cents, xp, est_seconds, content, repeatable, min_task_level, status, order_index)
  VALUES (
    t->>'kind', t->>'category', t->>'title', COALESCE(t->>'description',''),
    COALESCE(t->>'difficulty','easy'),
    COALESCE((t->>'reward_cents')::int, 2), COALESCE((t->>'xp')::int, 3),
    COALESCE((t->>'est_seconds')::int, 20), t->'content', false,
    COALESCE((t->>'min_task_level')::int, 1), 'published', 100 + i
  ) RETURNING id INTO new_id;
  IF t ? 'answer' AND jsonb_typeof(t->'answer') <> 'null' THEN
    INSERT INTO ai_task_answers (task_id, answer) VALUES (new_id, t->'answer');
  END IF;
END LOOP;
END $$;
