import { RealCourse } from "../types";

export const chatgptForWork: RealCourse = {
  slug: "chatgpt-for-work",
  category: "ai",
  difficulty: "beginner",
  description: "Use ChatGPT to do real work faster — writing, summarising, analysis, planning and automation — while keeping quality and privacy.",
  stages: [
    {
      title: "Foundations",
      chapters: [
        { title: "What ChatGPT is (and isn't)", summary: "ChatGPT predicts helpful text from your prompt; it's a powerful assistant, not a source of truth.",
          concepts: ["It generates language patterns, so it can sound confident yet be wrong ('hallucinate').", "It has no live internet unless a tool/browse mode is on.", "You must verify facts, numbers, names and quotes.", "It's best at drafting, rewriting, summarising and brainstorming."],
          steps: ["Open ChatGPT and send a clear task.", "Read the output critically.", "Verify any fact before using it.", "Edit to your voice before sending."],
          tips: ["Treat output as a first draft.", "Never trust unverified facts/figures."],
          mistakes: ["Copy-pasting answers as final truth.", "Assuming it knows today's news."],
          quiz: [
            { q: "When ChatGPT confidently states a false fact, this is called a:", options: ["Bug", "Hallucination", "Crash", "Feature"], answer: "Hallucination", explanation: "Models can produce confident but wrong output." },
            { q: "You should verify facts and figures from ChatGPT before using them.", options: ["True", "False"], answer: "True", explanation: "Always verify — it can be wrong." },
            { q: "ChatGPT is best treated as a first ____ , not a final answer.", answer: "draft", explanation: "Use it to draft, then review." },
          ] },
        { title: "Writing your first useful prompts", summary: "Clear prompts with role, task, context and format get far better results.",
          concepts: ["Give it a role ('Act as a recruiter').", "State the task and the desired format.", "Add context (audience, tone, length).", "Ask for options when unsure."],
          steps: ["Write the role + task in one line.", "Add context and constraints.", "Specify the output format.", "Refine with follow-ups."],
          tips: ["Be specific — vague prompts give vague answers.", "Iterate; don't expect perfection first try."],
          mistakes: ["One-word prompts.", "No format or context."],
          quiz: [
            { q: "A strong prompt usually includes a role, a task, context and a:", options: ["Password", "Desired output format", "Photo", "Random word"], answer: "Desired output format", explanation: "Format guides the structure of the answer." },
            { q: "More specific prompts generally produce better results.", options: ["True", "False"], answer: "True", explanation: "Specificity reduces ambiguity." },
          ] },
        { title: "Setting tone and audience", summary: "Telling ChatGPT who it's writing for and in what tone makes output usable.",
          concepts: ["Specify audience (e.g. 'busy CEO', 'new customer').", "Specify tone (formal, friendly, concise).", "Give a sample of the voice you want.", "Ask it to match your existing writing."],
          steps: ["Name the audience.", "Name the tone.", "Paste a sample of your style.", "Ask it to mirror that style."],
          tips: ["Paste a past email as a style guide.", "Ask for 'concise' to avoid fluff."],
          mistakes: ["Not specifying tone — output sounds robotic.", "Ignoring audience."],
          quiz: [
            { q: "To make ChatGPT match your writing style, you should:", options: ["Hope it guesses", "Paste a sample of your writing", "Use all caps", "Ask twice"], answer: "Paste a sample of your writing", explanation: "Examples teach it your voice." },
            { q: "Stating the audience helps ChatGPT pitch the message correctly.", options: ["True", "False"], answer: "True", explanation: "Audience shapes tone and detail." },
          ] },
        { title: "Privacy and safe use at work", summary: "Never paste secrets or client data into AI tools your client hasn't approved.",
          concepts: ["Don't paste passwords, financials or personal data.", "Check your employer/client's AI policy.", "Anonymise data before using AI on it.", "Keep a human in the loop for decisions."],
          steps: ["Confirm which tools are approved.", "Remove sensitive details before pasting.", "Review output for accuracy and tone.", "Get human sign-off on important sends."],
          tips: ["Anonymise then analyse.", "When unsure, leave it out."],
          mistakes: ["Pasting confidential data.", "Ignoring company AI policy."],
          quiz: [
            { q: "Before analysing data with AI you should:", options: ["Add more secrets", "Anonymise/remove sensitive details", "Share passwords", "Nothing"], answer: "Anonymise/remove sensitive details", explanation: "Protect privacy first." },
            { q: "It's safe to paste any client data into any AI tool.", options: ["True", "False"], answer: "False", explanation: "Only use approved tools and protect data." },
          ] },
      ],
    },
    {
      title: "Writing & Communication",
      chapters: [
        { title: "Drafting emails fast", summary: "ChatGPT drafts professional emails you then personalise.",
          concepts: ["Give it the goal, recipient and key points.", "Ask for a subject line too.", "Request 2 versions (formal/friendly).", "Always personalise before sending."],
          steps: ["List the points the email must make.", "Prompt for a draft + subject.", "Pick and edit the best version.", "Add a personal touch."],
          tips: ["Ask for shorter if it's wordy.", "Keep your real voice."],
          mistakes: ["Sending unedited drafts.", "Generic, impersonal emails."],
          quiz: [
            { q: "After ChatGPT drafts an email you should:", options: ["Send immediately", "Personalise and edit it", "Delete it", "Translate it"], answer: "Personalise and edit it", explanation: "Editing keeps it authentic and accurate." },
            { q: "Asking for two tone variations helps you pick the right fit.", options: ["True", "False"], answer: "True", explanation: "Options speed up choosing tone." },
          ] },
        { title: "Summarising long content", summary: "Turn long docs, threads and transcripts into clear summaries and action points.",
          concepts: ["Ask for a summary plus action items.", "Specify length ('5 bullets').", "Ask 'what decisions are needed?'", "Verify the summary against the source."],
          steps: ["Paste the content.", "Ask for bullet summary + actions.", "Request key decisions.", "Check accuracy."],
          tips: ["Ask for 'decisions needed' to drive action.", "Cap the length."],
          mistakes: ["Trusting a summary without checking.", "No action items."],
          quiz: [
            { q: "A useful summary for work should also surface:", options: ["Emojis", "Action items / decisions needed", "Fonts", "Ads"], answer: "Action items / decisions needed", explanation: "Summaries should drive next steps." },
            { q: "You should still verify an AI summary against the original.", options: ["True", "False"], answer: "True", explanation: "Summaries can miss or distort details." },
          ] },
        { title: "Rewriting and proofreading", summary: "Improve clarity, fix grammar, and adjust tone in seconds.",
          concepts: ["Ask it to fix grammar without changing meaning.", "Ask to make it clearer/shorter/friendlier.", "Use 'suggest improvements' for feedback.", "Keep final judgement yourself."],
          steps: ["Paste your text.", "State the change you want.", "Compare versions.", "Apply the best edits."],
          tips: ["Change one thing at a time.", "Keep your meaning intact."],
          mistakes: ["Letting it change your meaning.", "Over-editing into blandness."],
          quiz: [
            { q: "To tighten wordy text, a good instruction is:", options: ["'Make it longer'", "'Make it clearer and more concise'", "'Add jargon'", "'Translate'"], answer: "'Make it clearer and more concise'", explanation: "Clear, concise edits improve readability." },
            { q: "When proofreading, you can ask AI to fix grammar without changing meaning.", options: ["True", "False"], answer: "True", explanation: "Constrain edits to preserve intent." },
          ] },
        { title: "Brainstorming ideas", summary: "Use ChatGPT to generate options you curate.",
          concepts: ["Ask for many ideas, then narrow.", "Give constraints to focus ideas.", "Combine and refine the best.", "Push back: 'give bolder options'."],
          steps: ["State the goal and constraints.", "Ask for 10 ideas.", "Pick the top 3.", "Refine those further."],
          tips: ["Quantity first, then quality.", "Add constraints for relevance."],
          mistakes: ["Accepting the first idea.", "No constraints — vague ideas."],
          quiz: [
            { q: "A good brainstorming approach is to:", options: ["Ask for one idea", "Generate many, then curate the best", "Avoid constraints", "Use the first result"], answer: "Generate many, then curate the best", explanation: "Volume then selection yields better ideas." },
            { q: "Adding constraints makes brainstormed ideas more relevant.", options: ["True", "False"], answer: "True", explanation: "Constraints focus the output." },
          ] },
      ],
    },
    {
      title: "Productivity & Analysis",
      chapters: [
        { title: "Planning and to-do lists", summary: "Turn goals into structured plans and prioritised tasks.",
          concepts: ["Ask it to break a goal into steps.", "Prioritise with a method (e.g. impact/effort).", "Set realistic timelines.", "Review and adjust."],
          steps: ["State the goal and deadline.", "Ask for a step-by-step plan.", "Prioritise the steps.", "Add to your task tool."],
          tips: ["Ask 'what's the first step?'", "Keep plans realistic."],
          mistakes: ["Over-planning, never starting.", "No priorities."],
          quiz: [
            { q: "A good way to start a big goal is to ask ChatGPT to:", options: ["Do it for you", "Break it into clear steps", "Ignore it", "Add complexity"], answer: "Break it into clear steps", explanation: "Decomposition makes goals actionable." },
            { q: "Plans should be reviewed and adjusted as you go.", options: ["True", "False"], answer: "True", explanation: "Plans evolve with reality." },
          ] },
        { title: "Working with spreadsheets", summary: "Get formulas and explanations for Sheets/Excel tasks.",
          concepts: ["Describe your columns and goal to get a formula.", "Ask it to explain a formula you don't understand.", "Always test formulas on sample data.", "Watch ranges and references."],
          steps: ["Describe the data and the result you want.", "Get the formula.", "Test on a few rows.", "Adjust ranges as needed."],
          tips: ["Give column letters/headers for accuracy.", "Test before trusting."],
          mistakes: ["Pasting a formula without testing.", "Wrong cell ranges."],
          quiz: [
            { q: "After getting a spreadsheet formula from AI you should:", options: ["Trust it blindly", "Test it on sample data", "Delete the sheet", "Ignore ranges"], answer: "Test it on sample data", explanation: "Testing catches range/logic errors." },
            { q: "Telling AI your column headers helps it write the right formula.", options: ["True", "False"], answer: "True", explanation: "Context improves formula accuracy." },
          ] },
        { title: "Research and comparisons", summary: "Use AI to structure research, but verify the facts yourself.",
          concepts: ["Ask for a comparison table of options.", "Ask for pros/cons and a recommendation.", "Verify every fact independently.", "Note assumptions."],
          steps: ["Define what you're comparing.", "Ask for a structured table.", "Verify the details.", "Decide with the evidence."],
          tips: ["Structure first, verify second.", "Don't trust unverified numbers."],
          mistakes: ["Using AI 'facts' without checking.", "No clear decision."],
          quiz: [
            { q: "When AI gives you research facts, you must:", options: ["Trust them", "Verify them independently", "Publish them", "Ignore them"], answer: "Verify them independently", explanation: "AI can be wrong; verify." },
            { q: "A comparison table makes options easier to evaluate.", options: ["True", "False"], answer: "True", explanation: "Tables clarify trade-offs." },
          ] },
        { title: "Meeting notes and follow-ups", summary: "Turn rough notes or transcripts into clean minutes and action items.",
          concepts: ["Paste notes; ask for minutes + actions + owners.", "Ask for a follow-up email draft.", "Keep decisions explicit.", "Confirm with attendees."],
          steps: ["Paste the raw notes.", "Ask for structured minutes.", "Extract action items with owners.", "Draft the follow-up."],
          tips: ["Always capture owners + due dates.", "Send notes promptly."],
          mistakes: ["Notes with no action owners.", "Sending unverified minutes."],
          quiz: [
            { q: "Good meeting minutes always capture:", options: ["Only opinions", "Action items with owners and due dates", "Nothing", "Jokes"], answer: "Action items with owners and due dates", explanation: "Owners + deadlines drive follow-through." },
            { q: "AI can turn rough notes into structured minutes you then verify.", options: ["True", "False"], answer: "True", explanation: "Verify before sending." },
          ] },
      ],
    },
    {
      title: "Automation & Tools",
      chapters: [
        { title: "Reusable prompt templates", summary: "Save proven prompts so you get consistent results every time.",
          concepts: ["Build templates with placeholders ([audience], [goal]).", "Store them in a doc for reuse.", "Refine templates as you learn.", "Share team templates for consistency."],
          steps: ["Identify tasks you repeat.", "Write a template with placeholders.", "Save it where you can find it.", "Improve it over time."],
          tips: ["Use placeholders for the variable bits.", "Keep a personal prompt library."],
          mistakes: ["Rewriting prompts from scratch each time.", "No saved library."],
          quiz: [
            { q: "Prompt templates help you get:", options: ["Random results", "Consistent, repeatable results", "Errors", "Slower output"], answer: "Consistent, repeatable results", explanation: "Templates standardise quality." },
            { q: "Placeholders like [audience] make a template reusable.", options: ["True", "False"], answer: "True", explanation: "Placeholders adapt one template to many cases." },
          ] },
        { title: "Custom instructions & GPTs", summary: "Set persistent context so ChatGPT knows your role and preferences.",
          concepts: ["Custom instructions store your context across chats.", "Custom GPTs package a task with fixed instructions.", "Good context = less repeating yourself.", "Update as your needs change."],
          steps: ["Add your role and preferences to custom instructions.", "Create a GPT for a recurring task.", "Test and refine it.", "Reuse daily."],
          tips: ["Tell it your job and tone once.", "Build a GPT for repetitive jobs."],
          mistakes: ["Re-explaining context every chat.", "Stale instructions."],
          quiz: [
            { q: "Custom instructions are useful because they:", options: ["Slow it down", "Store your context so you don't repeat it", "Delete chats", "Cost money"], answer: "Store your context so you don't repeat it", explanation: "Persistent context saves time." },
            { q: "A custom GPT can package a repeated task with fixed instructions.", options: ["True", "False"], answer: "True", explanation: "GPTs encapsulate workflows." },
          ] },
        { title: "Connecting AI with other apps", summary: "Tools like Zapier let AI steps run inside automated workflows.",
          concepts: ["Automation = trigger → action, sometimes with an AI step.", "Example: new form entry → AI summarises → sent to Slack.", "Start with one simple, high-value automation.", "Test thoroughly before relying on it."],
          steps: ["Pick one repetitive workflow.", "Map trigger and actions.", "Add an AI step if helpful.", "Test with real data."],
          tips: ["Automate the boring, repeated stuff.", "Always test edge cases."],
          mistakes: ["Automating something rarely done.", "No testing — silent failures."],
          quiz: [
            { q: "A basic automation is structured as:", options: ["Action only", "Trigger → action", "Random", "Nothing"], answer: "Trigger → action", explanation: "Automations react to a trigger with actions." },
            { q: "You should test an automation before depending on it.", options: ["True", "False"], answer: "True", explanation: "Untested automations fail silently." },
          ] },
        { title: "Quality control with AI", summary: "Always keep a human check on AI output that goes to clients.",
          concepts: ["AI accelerates; humans approve.", "Check facts, tone, and bias.", "Have a checklist before sending.", "Own the final result yourself."],
          steps: ["Generate with AI.", "Review against a checklist.", "Fix issues.", "Approve and send."],
          tips: ["Never auto-send important AI output.", "Use a review checklist."],
          mistakes: ["Auto-sending unreviewed output.", "Trusting tone blindly."],
          quiz: [
            { q: "For client-facing AI output, the right rule is:", options: ["Auto-send", "Human reviews and approves before sending", "Never use AI", "Send twice"], answer: "Human reviews and approves before sending", explanation: "Keep a human in the loop." },
            { q: "A review checklist improves the quality of AI-assisted work.", options: ["True", "False"], answer: "True", explanation: "Checklists catch errors." },
          ] },
      ],
    },
    {
      title: "Getting Hired",
      chapters: [
        { title: "Packaging AI skills as a service", summary: "Offer concrete AI-powered services with clear outcomes.",
          concepts: ["Sell outcomes (e.g. 'inbox summaries', 'content drafts').", "Productise: fixed scope, fixed price.", "Show before/after examples.", "Target businesses drowning in admin/content."],
          steps: ["List AI tasks you do well.", "Package one as a clear offer.", "Create a sample result.", "Set a price."],
          tips: ["Name the outcome, not the tool.", "Show proof."],
          mistakes: ["Selling 'I know AI' vaguely.", "No examples."],
          quiz: [
            { q: "A strong AI service offer focuses on:", options: ["The tool's name", "The outcome the client gets", "Your hardware", "Nothing"], answer: "The outcome the client gets", explanation: "Clients buy outcomes." },
            { q: "Productising means fixed scope and fixed price.", options: ["True", "False"], answer: "True", explanation: "Productised services are easy to buy." },
          ] },
        { title: "Building an AI portfolio", summary: "Show real samples of AI-assisted work and the results.",
          concepts: ["Create before/after samples.", "Document a workflow you built.", "Get a testimonial.", "Keep it simple and visual."],
          steps: ["Pick 3 tasks to showcase.", "Make before/after examples.", "Write a short case note.", "Publish on a simple page."],
          tips: ["Quantify results where possible.", "Keep samples relevant."],
          mistakes: ["No tangible samples.", "Overclaiming."],
          quiz: [
            { q: "The best portfolio proof is:", options: ["Claims", "Real before/after samples and results", "A logo", "Nothing"], answer: "Real before/after samples and results", explanation: "Show, don't tell." },
            { q: "Quantifying results (e.g. 'cut time 60%') strengthens a portfolio.", options: ["True", "False"], answer: "True", explanation: "Numbers are persuasive." },
          ] },
        { title: "Finding AI-assistant clients", summary: "Target businesses with repetitive content/admin and pitch specific help.",
          concepts: ["Look for content-heavy or admin-heavy businesses.", "Pitch one specific automation/output.", "Use platforms + direct outreach.", "Follow up consistently."],
          steps: ["List target businesses.", "Find one painful, repetitive task.", "Pitch a specific AI solution.", "Follow up."],
          tips: ["Lead with their pain.", "Be specific."],
          mistakes: ["Generic pitches.", "No follow-up."],
          quiz: [
            { q: "A good AI-service pitch is:", options: ["Generic", "Specific to one of the client's repetitive tasks", "All about you", "Spam"], answer: "Specific to one of the client's repetitive tasks", explanation: "Specific pitches convert." },
            { q: "Content-heavy businesses are good targets for AI services.", options: ["True", "False"], answer: "True", explanation: "They have repetitive work to speed up." },
          ] },
        { title: "Staying current and ethical", summary: "Keep learning new tools and use AI responsibly and transparently.",
          concepts: ["Tools change fast — keep experimenting.", "Be transparent when appropriate.", "Avoid plagiarism and bias.", "Protect data and follow policies."],
          steps: ["Follow a couple of trusted AI sources.", "Test new features monthly.", "Disclose AI use where expected.", "Respect privacy."],
          tips: ["Block time to learn.", "Be honest about AI use."],
          mistakes: ["Falling behind on tools.", "Passing AI work off dishonestly where disclosure is expected."],
          quiz: [
            { q: "Responsible AI use at work includes:", options: ["Ignoring privacy", "Protecting data and following policy", "Plagiarism", "Hiding all use"], answer: "Protecting data and following policy", explanation: "Ethics and privacy matter." },
            { q: "AI tools change quickly, so ongoing learning is important.", options: ["True", "False"], answer: "True", explanation: "Stay current to stay valuable." },
          ] },
      ],
    },
  ],
};
