import { RealCourse } from "../types";

export const customerSupport: RealCourse = {
  slug: "customer-support",
  category: "support",
  difficulty: "beginner",
  description: "Deliver excellent remote customer support across email, chat and phone — and turn frustrated customers into loyal ones.",
  stages: [
    {
      title: "Support Foundations",
      chapters: [
        { title: "The role of customer support", summary: "Support solves problems and protects the relationship, not just answers tickets.",
          concepts: ["Support drives retention — keeping customers is cheaper than finding new ones.", "Every ticket is a chance to build loyalty.", "Speed + empathy + resolution = great support.", "You represent the whole company in each reply."],
          steps: ["Read the customer's message fully.", "Identify the real problem (not just the symptom).", "Solve it or escalate clearly.", "Confirm the customer is satisfied."],
          tips: ["Solve the problem behind the question.", "A calm tone de-escalates."],
          mistakes: ["Answering the literal question but missing the real need.", "Sounding robotic."],
          quiz: [
            { q: "Great customer support is mainly about:", options: ["Closing tickets fast at any cost", "Solving the problem and protecting the relationship", "Avoiding customers", "Upselling only"], answer: "Solving the problem and protecting the relationship", explanation: "Resolution + relationship build loyalty." },
            { q: "Keeping an existing customer is usually cheaper than acquiring a new one.", options: ["True", "False"], answer: "True", explanation: "Retention is cost-effective." },
            { q: "Great support combines speed, resolution and ____.", answer: "empathy", explanation: "Empathy is core to support." },
          ] },
        { title: "Channels: email, chat, phone", summary: "Each channel has a different pace and etiquette.",
          concepts: ["Email: thorough, well-structured, slower.", "Live chat: fast, concise, friendly.", "Phone: warm voice, active listening.", "Match tone and speed to the channel."],
          steps: ["Learn the expected response time per channel.", "Adapt your style to the channel.", "Keep records of each interaction.", "Hand off cleanly between channels."],
          tips: ["Chat: short, fast, human.", "Phone: smile — it's audible."],
          mistakes: ["Writing essays in live chat.", "Being curt on the phone."],
          quiz: [
            { q: "Live chat replies should be:", options: ["Long essays", "Short, fast and friendly", "Silent", "Formal letters"], answer: "Short, fast and friendly", explanation: "Chat is quick and conversational." },
            { q: "Tone and pace should match the support channel.", options: ["True", "False"], answer: "True", explanation: "Each channel has its own etiquette." },
          ] },
        { title: "Tone, empathy and clarity", summary: "Acknowledge feelings, then solve clearly.",
          concepts: ["Acknowledge the customer's frustration first.", "Use plain language, not jargon.", "Be positive: say what you can do.", "Confirm understanding before solving."],
          steps: ["Acknowledge: 'I understand how frustrating this is.'", "Restate the issue to confirm.", "Explain the solution simply.", "Check they're happy."],
          tips: ["Empathise before you fix.", "Avoid jargon."],
          mistakes: ["Jumping to a fix without acknowledging.", "Using internal jargon."],
          quiz: [
            { q: "Before solving a frustrated customer's problem, you should first:", options: ["Defend the company", "Acknowledge their feelings", "Hang up", "Upsell"], answer: "Acknowledge their feelings", explanation: "Empathy de-escalates." },
            { q: "Using plain language instead of jargon helps customers.", options: ["True", "False"], answer: "True", explanation: "Clarity reduces confusion." },
          ] },
        { title: "Product knowledge", summary: "You can't support what you don't understand.",
          concepts: ["Know the product deeply — features, limits, common issues.", "Keep a personal FAQ/notes doc.", "Know where to find answers fast.", "Test the product like a customer."],
          steps: ["Use the product yourself.", "Build a notes doc of common issues.", "Learn the escalation paths.", "Keep notes updated."],
          tips: ["Be the product's best user.", "Document as you learn."],
          mistakes: ["Guessing answers.", "Never using the product."],
          quiz: [
            { q: "The best way to give accurate answers is to:", options: ["Guess", "Know the product deeply and use it yourself", "Ask the customer", "Ignore it"], answer: "Know the product deeply and use it yourself", explanation: "First-hand knowledge = accurate support." },
            { q: "Keeping a personal notes/FAQ doc speeds up future replies.", options: ["True", "False"], answer: "True", explanation: "Notes prevent re-solving the same issue." },
          ] },
      ],
    },
    {
      title: "Handling Tickets",
      chapters: [
        { title: "Anatomy of a great reply", summary: "Acknowledge, answer, next steps, close warmly.",
          concepts: ["Greet and acknowledge.", "Give a clear, complete answer.", "State next steps or set expectations.", "Close warmly and invite follow-up."],
          steps: ["Acknowledge the issue.", "Answer fully and simply.", "Tell them what happens next.", "Invite them to reply if needed."],
          tips: ["One reply should resolve, not bounce.", "End with an open door."],
          mistakes: ["Vague replies that need 3 follow-ups.", "No next steps."],
          quiz: [
            { q: "A great support reply aims to:", options: ["Bounce the ticket", "Fully resolve in as few replies as possible", "Be as long as possible", "Avoid the question"], answer: "Fully resolve in as few replies as possible", explanation: "First-contact resolution is the goal." },
            { q: "Setting clear next steps reduces back-and-forth.", options: ["True", "False"], answer: "True", explanation: "Expectations cut follow-ups." },
          ] },
        { title: "Using macros and templates", summary: "Templates speed replies — but personalise them.",
          concepts: ["Macros handle common questions consistently.", "Personalise with the customer's name and detail.", "Keep templates updated.", "Never sound copy-pasted."],
          steps: ["Build templates for top issues.", "Insert and personalise per ticket.", "Edit for the specific situation.", "Review templates monthly."],
          tips: ["Always tweak the template.", "Keep a shared, current macro set."],
          mistakes: ["Sending raw, impersonal macros.", "Outdated templates."],
          quiz: [
            { q: "When using a template/macro you should:", options: ["Send it raw", "Personalise it to the customer", "Hide it", "Skip greetings"], answer: "Personalise it to the customer", explanation: "Personalisation keeps it human." },
            { q: "Macros help give consistent answers to common questions.", options: ["True", "False"], answer: "True", explanation: "Consistency improves quality." },
          ] },
        { title: "Prioritising and SLAs", summary: "Handle urgent and high-impact tickets first, within agreed times.",
          concepts: ["SLA = the promised response/resolution time.", "Triage by urgency and impact.", "Communicate if you'll be late.", "Don't let tickets go stale."],
          steps: ["Sort the queue by priority.", "Tackle urgent/high-impact first.", "Update customers on waits.", "Clear stale tickets."],
          tips: ["Urgent + high-impact = first.", "A quick 'still working on it' buys patience."],
          mistakes: ["First-in-first-out ignoring urgency.", "Silent delays."],
          quiz: [
            { q: "SLA stands for the agreed:", options: ["Sales Lead Amount", "Service Level Agreement (response/resolution time)", "System Log Archive", "Support List App"], answer: "Service Level Agreement (response/resolution time)", explanation: "SLAs define promised timings." },
            { q: "Tickets should be prioritised by urgency and impact, not just order.", options: ["True", "False"], answer: "True", explanation: "Triage beats strict FIFO." },
          ] },
        { title: "Escalating correctly", summary: "Know when and how to pass an issue up — with full context.",
          concepts: ["Escalate when it's beyond your access or knowledge.", "Include all context so it isn't re-asked.", "Set the customer's expectations.", "Follow up until resolved."],
          steps: ["Identify it needs escalation.", "Summarise the full context.", "Route to the right team.", "Keep the customer informed."],
          tips: ["Escalate with context, not just 'help'.", "Own it until it's solved."],
          mistakes: ["Dumping tickets with no context.", "Going silent after escalating."],
          quiz: [
            { q: "When escalating a ticket you should include:", options: ["Nothing", "Full context so it isn't re-investigated", "Only the ticket number", "An emoji"], answer: "Full context so it isn't re-investigated", explanation: "Context speeds resolution." },
            { q: "You should keep the customer informed even after escalating.", options: ["True", "False"], answer: "True", explanation: "Silence frustrates customers." },
          ] },
      ],
    },
    {
      title: "Difficult Situations",
      chapters: [
        { title: "De-escalating angry customers", summary: "Stay calm, acknowledge, and focus on the fix.",
          concepts: ["Don't take anger personally.", "Acknowledge and apologise for the impact.", "Move to solving quickly.", "Stay calm and professional."],
          steps: ["Let them vent briefly.", "Acknowledge and apologise.", "Refocus on the solution.", "Confirm resolution."],
          tips: ["Lower your tone, not your standards.", "Solve, don't argue."],
          mistakes: ["Getting defensive.", "Matching their anger."],
          quiz: [
            { q: "With an angry customer, your first move is to:", options: ["Argue", "Acknowledge and apologise for the impact", "Hang up", "Blame them"], answer: "Acknowledge and apologise for the impact", explanation: "Acknowledgement de-escalates." },
            { q: "You should take customer anger personally.", options: ["True", "False"], answer: "False", explanation: "It's about the problem, not you." },
          ] },
        { title: "Saying no gracefully", summary: "Decline requests you can't fulfil while keeping goodwill.",
          concepts: ["Explain what you can do, not just what you can't.", "Offer an alternative if possible.", "Be honest, not vague.", "Keep empathy in a 'no'."],
          steps: ["Acknowledge the request.", "Explain honestly why it isn't possible.", "Offer an alternative.", "Stay warm."],
          tips: ["Pivot to what's possible.", "Honesty beats false promises."],
          mistakes: ["Hard 'no' with no alternative.", "Over-promising to avoid saying no."],
          quiz: [
            { q: "When you must say no, you should also:", options: ["Offer what you can do / an alternative", "Be rude", "Promise anyway", "Ignore them"], answer: "Offer what you can do / an alternative", explanation: "Alternatives preserve goodwill." },
            { q: "Over-promising to avoid a 'no' usually backfires.", options: ["True", "False"], answer: "True", explanation: "Broken promises destroy trust." },
          ] },
        { title: "Mistakes and refunds", summary: "Own errors fast and follow the refund policy fairly.",
          concepts: ["Apologise sincerely for genuine mistakes.", "Know and apply the policy consistently.", "Make the fix easy for the customer.", "Learn from the error."],
          steps: ["Acknowledge the mistake.", "Apply the correct policy.", "Resolve quickly.", "Prevent recurrence."],
          tips: ["A fast, fair fix wins loyalty.", "Be consistent with policy."],
          mistakes: ["Defending an obvious error.", "Applying policy inconsistently."],
          quiz: [
            { q: "When the company clearly made a mistake, you should:", options: ["Deny it", "Apologise and fix it fairly", "Blame the customer", "Delay"], answer: "Apologise and fix it fairly", explanation: "Owning errors builds trust." },
            { q: "Refund/policy decisions should be applied consistently.", options: ["True", "False"], answer: "True", explanation: "Consistency is fair and defensible." },
          ] },
        { title: "Turning complaints into loyalty", summary: "A well-handled complaint can create a bigger fan than no problem at all.",
          concepts: ["The 'service recovery paradox': great recovery boosts loyalty.", "Follow up after resolving.", "Thank them for the feedback.", "Fix the root cause."],
          steps: ["Resolve the complaint well.", "Follow up to confirm satisfaction.", "Thank them.", "Report the root cause internally."],
          tips: ["Follow up — it surprises customers.", "Feed issues back to the team."],
          mistakes: ["Resolving then disappearing.", "Ignoring root causes."],
          quiz: [
            { q: "A brilliantly handled complaint can:", options: ["Always lose the customer", "Increase loyalty (service recovery paradox)", "Do nothing", "Only annoy them"], answer: "Increase loyalty (service recovery paradox)", explanation: "Great recovery can deepen loyalty." },
            { q: "Following up after resolving a complaint is good practice.", options: ["True", "False"], answer: "True", explanation: "Follow-up shows you care." },
          ] },
      ],
    },
    {
      title: "Tools & Metrics",
      chapters: [
        { title: "Helpdesk tools (Zendesk, Intercom)", summary: "Ticketing tools organise, route and track conversations.",
          concepts: ["Tickets keep every conversation in one place.", "Tags and assignment route work.", "Saved replies speed common answers.", "Reporting shows team performance."],
          steps: ["Learn to create, tag and assign tickets.", "Use saved replies.", "Track status to closure.", "Read your reports."],
          tips: ["Tag consistently for good reporting.", "Keep ticket status current."],
          mistakes: ["Inconsistent tagging.", "Leaving tickets unassigned."],
          quiz: [
            { q: "Helpdesk tools mainly help you:", options: ["Design logos", "Organise, route and track support conversations", "Edit video", "Write code"], answer: "Organise, route and track support conversations", explanation: "They centralise support work." },
            { q: "Consistent tagging improves support reporting.", options: ["True", "False"], answer: "True", explanation: "Tags power useful metrics." },
          ] },
        { title: "Key support metrics", summary: "CSAT, response time, resolution time and FCR show how you're doing.",
          concepts: ["CSAT = customer satisfaction score.", "First response time matters to customers.", "First-contact resolution (FCR) reduces effort.", "Don't game metrics at the expense of customers."],
          steps: ["Track your response and resolution times.", "Watch CSAT after interactions.", "Aim to resolve on first contact.", "Improve from the data."],
          tips: ["Aim for high FCR.", "Quality over vanity metrics."],
          mistakes: ["Closing tickets fast but unresolved.", "Chasing numbers, not satisfaction."],
          quiz: [
            { q: "CSAT measures:", options: ["Server uptime", "Customer satisfaction", "Code quality", "Ad clicks"], answer: "Customer satisfaction", explanation: "CSAT = customer satisfaction." },
            { q: "Closing tickets quickly without resolving them is good practice.", options: ["True", "False"], answer: "False", explanation: "Unresolved closes hurt customers and metrics." },
          ] },
        { title: "Knowledge bases and self-service", summary: "Good help articles deflect tickets and empower customers.",
          concepts: ["Write clear, step-by-step help articles.", "Use screenshots for clarity.", "Keep articles updated.", "Link articles in replies."],
          steps: ["Identify the top repeated questions.", "Write a clear article each.", "Add visuals.", "Share links proactively."],
          tips: ["Turn repeated tickets into articles.", "Keep docs current."],
          mistakes: ["Outdated help docs.", "Walls of text, no steps."],
          quiz: [
            { q: "A good knowledge base reduces tickets by:", options: ["Hiding info", "Letting customers self-serve clear answers", "Being vague", "Removing search"], answer: "Letting customers self-serve clear answers", explanation: "Self-service deflects repetitive tickets." },
            { q: "Repeated questions are good candidates for help articles.", options: ["True", "False"], answer: "True", explanation: "Document what's asked often." },
          ] },
        { title: "AI in support", summary: "AI drafts replies and summarises — agents verify and add the human touch.",
          concepts: ["AI suggests replies you review.", "AI summarises long ticket histories.", "Keep empathy and judgement human.", "Verify AI answers against the product."],
          steps: ["Use AI to draft a reply.", "Edit for accuracy and empathy.", "Summarise long threads with AI.", "Always verify."],
          tips: ["AI drafts; you approve.", "Never lose the human tone."],
          mistakes: ["Auto-sending AI replies.", "Losing empathy to speed."],
          quiz: [
            { q: "The right way to use AI for support replies is to:", options: ["Auto-send them", "Use as a draft you review and personalise", "Never reply", "Ignore the customer"], answer: "Use as a draft you review and personalise", explanation: "Human-verified AI keeps quality." },
            { q: "AI can summarise a long ticket history to save agent time.", options: ["True", "False"], answer: "True", explanation: "Summaries speed context-gathering." },
          ] },
      ],
    },
    {
      title: "Getting Hired",
      chapters: [
        { title: "Building support experience", summary: "Practise with real scenarios and document your wins.",
          concepts: ["Practise replies to sample tickets.", "Learn one helpdesk tool well.", "Collect metrics/wins where you can.", "Volunteer/intern to get real reps."],
          steps: ["Write sample replies to practice tickets.", "Learn a helpdesk tool.", "Record results you achieve.", "Get real practice."],
          tips: ["Sample tickets = portfolio.", "Know one tool deeply."],
          mistakes: ["No practical examples.", "Knowing zero tools."],
          quiz: [
            { q: "With no job yet, you can build proof by:", options: ["Waiting", "Writing sample replies and learning a helpdesk tool", "Nothing", "Complaining"], answer: "Writing sample replies and learning a helpdesk tool", explanation: "Practice builds demonstrable skill." },
            { q: "Knowing one helpdesk tool well helps you get hired.", options: ["True", "False"], answer: "True", explanation: "Tool fluency is valued." },
          ] },
        { title: "Your support resume and profile", summary: "Highlight communication, problem-solving and any metrics.",
          concepts: ["Lead with communication and empathy.", "Show problem-solving with examples.", "Add metrics (CSAT, resolution).", "Tailor to the role."],
          steps: ["Write a clear summary.", "Add 2–3 example wins.", "Include any metrics.", "Tailor per application."],
          tips: ["Numbers stand out.", "Tailor every application."],
          mistakes: ["Generic resume.", "No examples."],
          quiz: [
            { q: "A support resume is stronger when it includes:", options: ["Only hobbies", "Examples and metrics (e.g. CSAT)", "A long essay", "Nothing"], answer: "Examples and metrics (e.g. CSAT)", explanation: "Evidence and numbers persuade." },
            { q: "Tailoring your application to each role improves results.", options: ["True", "False"], answer: "True", explanation: "Relevance wins." },
          ] },
        { title: "Acing the support interview", summary: "Expect role-plays; show empathy and structured problem-solving.",
          concepts: ["Interviews often include a mock ticket or role-play.", "Show empathy out loud.", "Explain your reasoning.", "Ask about their tools and process."],
          steps: ["Prepare example stories (STAR).", "Practise a mock reply.", "Verbalise empathy and steps.", "Ask smart questions."],
          tips: ["Think out loud in role-plays.", "Lead with empathy."],
          mistakes: ["Jumping to solutions without empathy.", "No questions for them."],
          quiz: [
            { q: "Support interviews often test you with:", options: ["A coding test", "A mock ticket / role-play", "A drawing", "Nothing"], answer: "A mock ticket / role-play", explanation: "Role-plays reveal real skills." },
            { q: "Showing empathy during an interview role-play matters.", options: ["True", "False"], answer: "True", explanation: "Empathy is the core skill." },
          ] },
        { title: "Growing into senior and CS roles", summary: "Strong support can grow into team lead, QA, or customer success.",
          concepts: ["Master the basics, then specialise.", "Mentoring/QA opens lead roles.", "Customer Success is a higher-paid path.", "Keep learning the product and customers."],
          steps: ["Be excellent at the fundamentals.", "Help teammates / improve docs.", "Learn the CS/retention side.", "Aim for the next role."],
          tips: ["Lift the team to grow yourself.", "Eye the CS path for higher pay."],
          mistakes: ["Staying purely reactive.", "Never developing new skills."],
          quiz: [
            { q: "A common higher-paid growth path from support is:", options: ["Customer Success", "Janitor", "Driver", "None"], answer: "Customer Success", explanation: "CS builds on support skills and pays more." },
            { q: "Helping teammates and improving docs can open lead roles.", options: ["True", "False"], answer: "True", explanation: "Leadership behaviours get noticed." },
          ] },
      ],
    },
  ],
};
