import { RealCourse } from "../types";

export const virtualAssistant: RealCourse = {
  slug: "virtual-assistant",
  category: "admin",
  difficulty: "beginner",
  description: "Become a sought-after remote Virtual Assistant: manage inboxes, calendars, research, tools and clients — and land the work.",
  stages: [
    {
      title: "Foundations of Virtual Assistance",
      chapters: [
        {
          title: "What a Virtual Assistant really does",
          summary: "A VA handles a business owner's repetitive and administrative work remotely so they can focus on growth.",
          concepts: [
            "A VA is a remote contractor, not an employee — you bill by the hour or by package.",
            "Common tasks: email, calendar, data entry, research, travel booking, customer replies, social media.",
            "VAs are hired to save the client time and reduce their stress, not just to 'do tasks'.",
            "Specialised VAs (e.g. real-estate VA, e-commerce VA) earn more than general VAs.",
          ],
          steps: [
            "List tasks you can already do (email, typing, scheduling, research).",
            "Decide whether to start as a general VA or pick a niche.",
            "Write a one-line promise, e.g. 'I help busy founders reclaim 10 hours a week.'",
            "Set a starting rate (research shows $5–$15/hr is common for new VAs globally).",
          ],
          example: "A coach hires a VA for 10 hrs/week to clear her inbox, schedule calls and post 3 times a week on Instagram — freeing her to coach more clients.",
          tips: ["Sell the outcome (time saved), not the task list.", "Track everything you do — it becomes proof for future clients."],
          mistakes: ["Saying 'I can do anything' — vague offers don't get hired.", "Underpricing so low you burn out."],
          resources: ["belay.com/blog (VA industry)", "r/virtualassistants"],
          quiz: [
            { q: "A Virtual Assistant is best described as a:", options: ["Full-time employee", "Remote contractor who handles a client's tasks", "Software tool", "Recruiter"], answer: "Remote contractor who handles a client's tasks", explanation: "VAs are independent contractors hired remotely." },
            { q: "Specialised VAs (e.g. e-commerce) usually earn more than general VAs.", options: ["True", "False"], answer: "True", explanation: "Niche expertise commands higher rates." },
            { q: "The main reason clients hire VAs is to ____ them time.", answer: "save", explanation: "VAs are hired primarily to save the client time." },
            { q: "A client is overwhelmed and disorganised. Your best opening offer is:", options: ["'I can do anything you need'", "'I'll clear your inbox and run your calendar so you get 8 hours back each week'", "'I'm cheap'", "'I only do data entry'"], answer: "'I'll clear your inbox and run your calendar so you get 8 hours back each week'", explanation: "A specific, outcome-focused promise wins work." },
          ],
        },
        {
          title: "Skills and tools you need to start",
          summary: "You need reliable internet, core software skills, and strong communication — not a degree.",
          concepts: [
            "Hard skills: typing speed, Google Workspace/Microsoft Office, basic spreadsheets, email etiquette.",
            "Soft skills: clear written English, reliability, attention to detail, discretion with private info.",
            "Essential setup: a laptop, stable internet, a quiet space, and a backup (phone hotspot).",
            "You don't need paid tools to start — most have free tiers.",
          ],
          steps: [
            "Test and improve your typing speed (aim 45+ wpm) at typingtest.com.",
            "Create a professional Gmail and Google account.",
            "Practise writing short, polite, clear emails.",
            "Set up a free password manager to handle client logins safely.",
          ],
          tips: ["Keep a 'second brain' doc of how you do each task.", "Always have a backup internet plan."],
          mistakes: ["Sharing client passwords over plain email.", "Promising skills you can't yet deliver."],
          quiz: [
            { q: "Which is the most important soft skill for a VA?", options: ["Graphic design", "Clear, reliable communication", "Video editing", "Coding"], answer: "Clear, reliable communication", explanation: "Clients value reliability and clarity above flashy skills." },
            { q: "You should store client passwords in a password manager, not in plain email.", options: ["True", "False"], answer: "True", explanation: "Password managers protect client data." },
            { q: "A good typing speed target for a VA is at least ____ wpm.", answer: "45", explanation: "45+ wpm keeps you efficient." },
          ],
        },
        {
          title: "Setting up a professional workspace",
          summary: "A tidy digital and physical setup makes you faster and more trustworthy.",
          concepts: [
            "Digital workspace: organised Google Drive folders, labelled inbox, a task list.",
            "Physical workspace: quiet, good lighting for calls, headset with mic.",
            "Time zones: know your client's zone and your overlap hours.",
            "Boundaries: set working hours so you don't answer at 2am.",
          ],
          steps: [
            "Create Drive folders: /Clients, /Templates, /Admin.",
            "Set your calendar to show the client's time zone.",
            "Make a daily start-up checklist (inbox, calendar, tasks).",
            "Agree working hours and response times with each client.",
          ],
          tips: ["Use email labels/filters to triage automatically.", "Batch similar tasks to save time."],
          mistakes: ["No folder system — wasting time hunting for files.", "Being 'always on' and burning out."],
          quiz: [
            { q: "Why does knowing your client's time zone matter?", options: ["It doesn't", "To schedule calls and replies during their working hours", "To charge more", "To avoid taxes"], answer: "To schedule calls and replies during their working hours", explanation: "Time-zone awareness prevents missed meetings." },
            { q: "Batching similar tasks together makes you slower.", options: ["True", "False"], answer: "False", explanation: "Batching reduces context-switching and saves time." },
            { q: "A simple Drive structure might include /Clients, /Templates and /____.", answer: "Admin", explanation: "Separating admin keeps things organised." },
          ],
        },
        {
          title: "Choosing your niche",
          summary: "Picking a niche makes you easier to hire and lets you charge more.",
          concepts: [
            "Niche by industry (real estate, coaching, e-commerce) or by skill (inbox VA, podcast VA).",
            "A niche makes your marketing specific and your skills deeper.",
            "You can start general and niche down once you see what you enjoy.",
            "Niches with money and recurring work pay best.",
          ],
          steps: [
            "List industries you understand or enjoy.",
            "Check job boards for demand in that niche.",
            "Pick one and tailor your profile headline to it.",
            "Learn the 2–3 tools that niche uses most.",
          ],
          example: "A VA who niches into 'real-estate VA' learns the CRM and listing tools agents use, then charges $20/hr instead of $8.",
          tips: ["Choose a niche with budget and repeat work.", "Speak the niche's language in your profile."],
          mistakes: ["Staying too general forever.", "Picking a niche with no spending power."],
          quiz: [
            { q: "A key benefit of choosing a niche is that you can:", options: ["Work less", "Charge more and market more specifically", "Avoid clients", "Skip learning tools"], answer: "Charge more and market more specifically", explanation: "Specialists command higher rates." },
            { q: "You must pick your final niche before taking any client.", options: ["True", "False"], answer: "False", explanation: "You can start general and niche down later." },
          ],
        },
      ],
    },
    {
      title: "Core VA Skills",
      chapters: [
        {
          title: "Email and inbox management",
          summary: "Owning a client's inbox means triaging, replying, and keeping it near zero.",
          concepts: [
            "Triage = sort into Action, Waiting, Reference, and Delete/Archive.",
            "Use labels/folders and filters to auto-sort routine mail.",
            "Templates (canned responses) handle repetitive replies fast.",
            "Flag anything sensitive or unclear for the client instead of guessing.",
          ],
          steps: [
            "Agree which emails you can answer vs. must forward.",
            "Create 5–10 reply templates for common messages.",
            "Set filters to label newsletters, invoices, and clients.",
            "Process to inbox-zero daily; leave only items awaiting reply.",
          ],
          example: "A VA reduces a founder's 300-email backlog to 12 by archiving newsletters, templating FAQs, and flagging 12 real decisions for the founder.",
          tips: ["Touch each email once — decide, don't re-read.", "Keep a shared doc of approved reply wording."],
          mistakes: ["Replying on the client's behalf without permission.", "Letting the inbox pile back up."],
          quiz: [
            { q: "What does 'triage' mean for an inbox?", options: ["Delete everything", "Sort emails by what action they need", "Reply to all at once", "Ignore them"], answer: "Sort emails by what action they need", explanation: "Triage groups mail by required action." },
            { q: "Canned responses/templates help you handle repetitive emails faster.", options: ["True", "False"], answer: "True", explanation: "Templates speed up routine replies." },
            { q: "Aiming to clear the inbox each day is called inbox-____.", answer: "zero", explanation: "Inbox-zero means no unprocessed mail." },
            { q: "An email needs a decision only the client can make. You should:", options: ["Guess and reply", "Delete it", "Flag/forward it to the client", "Ignore it"], answer: "Flag/forward it to the client", explanation: "Escalate decisions you're not authorised to make." },
          ],
        },
        {
          title: "Calendar and scheduling",
          summary: "Great scheduling means no double-bookings, clear buffers, and correct time zones.",
          concepts: [
            "Always confirm the time zone before booking anything.",
            "Add buffers between meetings so the client isn't back-to-back.",
            "Scheduling tools (Calendly) let people book open slots automatically.",
            "Protect focus time by blocking it on the calendar.",
          ],
          steps: [
            "Set the calendar's default time zone and display a second zone.",
            "Create event templates (15/30/60 min) with buffers.",
            "Set up a Calendly link with the client's real availability.",
            "Send invites with agenda, link, and dial-in details.",
          ],
          tips: ["Double-check AM/PM and time zone on every invite.", "Block 'no-meeting' focus time."],
          mistakes: ["Booking across time zones incorrectly.", "No buffer — the client runs late all day."],
          quiz: [
            { q: "The most common scheduling error a VA must avoid is:", options: ["Wrong font", "Time-zone / AM-PM mistakes", "Too many colours", "Long titles"], answer: "Time-zone / AM-PM mistakes", explanation: "Time-zone errors cause missed meetings." },
            { q: "Buffers between meetings help the client avoid being back-to-back all day.", options: ["True", "False"], answer: "True", explanation: "Buffers protect time and energy." },
            { q: "A tool that lets people self-book open slots is ____.", answer: "Calendly", explanation: "Calendly automates booking." },
          ],
        },
        {
          title: "Research and travel booking",
          summary: "Clients pay VAs to find options fast and present clear recommendations.",
          concepts: [
            "Good research ends in a short recommendation, not 40 links.",
            "Compare options in a simple table (price, pros, cons).",
            "For travel: check times, layovers, visa needs, and the client's preferences.",
            "Always note your sources so the client can verify.",
          ],
          steps: [
            "Clarify the goal and any constraints (budget, dates, preferences).",
            "Gather 3 strong options, not everything.",
            "Summarise in a table with a clear recommendation.",
            "Book only after the client approves.",
          ],
          example: "Asked to find a hotel, a VA sends 3 options in a table with price, distance to the venue, and a one-line 'I recommend #2' — the client approves in 30 seconds.",
          tips: ["Lead with your recommendation.", "Keep receipts and confirmations organised."],
          mistakes: ["Dumping raw links with no summary.", "Booking before approval."],
          quiz: [
            { q: "Good research for a client should end with:", options: ["Every link you found", "A short comparison and a clear recommendation", "No conclusion", "Just a price"], answer: "A short comparison and a clear recommendation", explanation: "Clients want a decision-ready summary." },
            { q: "You should book travel only after the client approves the option.", options: ["True", "False"], answer: "True", explanation: "Always get approval before spending." },
          ],
        },
        {
          title: "Data entry and file organisation",
          summary: "Accuracy and consistent naming make data and files instantly usable.",
          concepts: [
            "Consistency beats speed — one naming convention everywhere.",
            "Validate data (no duplicates, correct formats) before delivering.",
            "Use templates so every record has the same fields.",
            "Name files like 2026-02-Invoice-ClientName so they sort by date.",
          ],
          steps: [
            "Agree a naming convention with the client.",
            "Use a template/sheet with set columns.",
            "Enter data carefully, then re-check a sample.",
            "Organise files into dated, clearly named folders.",
          ],
          tips: ["Use spreadsheet data validation to prevent errors.", "Date-prefix files: YYYY-MM-DD."],
          mistakes: ["Inconsistent naming — files become unfindable.", "No final accuracy check."],
          quiz: [
            { q: "The most important quality in data entry is:", options: ["Speed", "Accuracy and consistency", "Colour", "Length"], answer: "Accuracy and consistency", explanation: "Wrong data is worse than slow data." },
            { q: "Naming files with a YYYY-MM-DD prefix helps them sort by date.", options: ["True", "False"], answer: "True", explanation: "Date prefixes give chronological sorting." },
            { q: "Spreadsheet 'data ____' stops invalid entries.", answer: "validation", explanation: "Data validation enforces correct formats." },
          ],
        },
      ],
    },
    {
      title: "Tools & Workflows",
      chapters: [
        {
          title: "Mastering Google Workspace",
          summary: "Docs, Sheets, Drive, Gmail and Calendar are the VA's daily toolkit.",
          concepts: [
            "Docs for documents, Sheets for data, Drive for storage, all shareable.",
            "Sharing settings control who can view/comment/edit — be careful with 'anyone with link'.",
            "Comments and 'Suggesting' mode enable collaboration without overwriting.",
            "Version history lets you recover earlier drafts.",
          ],
          steps: [
            "Organise Drive with a clear folder tree.",
            "Practise sharing with view/comment/edit correctly.",
            "Use Suggesting mode when editing a client's doc.",
            "Learn 5 Sheets formulas: SUM, IF, VLOOKUP, COUNTIF, TEXT.",
          ],
          tips: ["Default to least-access sharing.", "Use version history to undo mistakes."],
          mistakes: ["Setting docs to public by accident.", "Editing over a client's text instead of suggesting."],
          quiz: [
            { q: "When editing a client's document, the safest mode is:", options: ["Editing directly", "Suggesting mode", "Delete and retype", "View only"], answer: "Suggesting mode", explanation: "Suggestions are reversible and reviewable." },
            { q: "'Anyone with the link can edit' is a safe default for client files.", options: ["True", "False"], answer: "False", explanation: "Default to least access to protect data." },
          ],
        },
        {
          title: "Task and project tools (Trello, Asana)",
          summary: "Boards and task lists keep client work visible and nothing slips.",
          concepts: [
            "Boards/lists show task status: To do, Doing, Done.",
            "Each task needs an owner and a due date.",
            "Checklists break big tasks into steps.",
            "Comments keep all context on the task, not in scattered chats.",
          ],
          steps: [
            "Create a board for the client's work.",
            "Add tasks with due dates and owners.",
            "Update status daily so the client sees progress.",
            "Use checklists for multi-step tasks.",
          ],
          tips: ["Keep one source of truth for tasks.", "Update statuses before you log off."],
          mistakes: ["Tasks with no due date or owner.", "Letting the board go stale."],
          quiz: [
            { q: "Every task on a board should have at minimum:", options: ["A colour", "An owner and a due date", "A photo", "A label only"], answer: "An owner and a due date", explanation: "Ownership and deadlines prevent slips." },
            { q: "A task board should be updated regularly so the client sees progress.", options: ["True", "False"], answer: "True", explanation: "A stale board hides status." },
          ],
        },
        {
          title: "Communication tools (Slack, Zoom, Loom)",
          summary: "Clear, prompt communication is what clients remember most.",
          concepts: [
            "Slack/email for text; Zoom for calls; Loom for quick screen recordings.",
            "Acknowledge messages fast, even if the full answer comes later.",
            "Over-communicate progress; silence makes clients anxious.",
            "Record how-to walkthroughs with Loom to save repeat explaining.",
          ],
          steps: [
            "Agree the main channel and expected response time.",
            "Send a short daily or end-of-day update.",
            "Use Loom to explain anything visual.",
            "Confirm receipt of tasks: 'Got it, will deliver by 3pm.'",
          ],
          tips: ["A 10-second 'on it' beats hours of silence.", "Summarise calls in writing afterwards."],
          mistakes: ["Going quiet for a day.", "Long calls with no written summary."],
          quiz: [
            { q: "If you can't finish a task immediately, you should first:", options: ["Stay silent", "Acknowledge and give a timeline", "Decline", "Wait a day"], answer: "Acknowledge and give a timeline", explanation: "Prompt acknowledgement builds trust." },
            { q: "Loom is useful for recording quick screen walkthroughs.", options: ["True", "False"], answer: "True", explanation: "Loom captures screen + voice explanations." },
          ],
        },
        {
          title: "AI tools that make VAs faster",
          summary: "AI drafts, summarises and organises — you review and finalise.",
          concepts: [
            "Use AI to draft emails, summarise long threads, and brainstorm.",
            "Always review AI output for accuracy and tone before sending.",
            "AI can turn messy notes into clean meeting minutes.",
            "Never paste a client's private data into tools they haven't approved.",
          ],
          steps: [
            "Draft a reply with AI, then edit for the client's voice.",
            "Summarise long email threads before escalating.",
            "Generate first-draft SOPs, then refine.",
            "Confirm which AI tools the client allows.",
          ],
          example: "A VA pastes a 20-message thread into an AI tool, gets a 4-line summary, and sends the client a clear decision request instead of the whole thread.",
          tips: ["AI is a first draft, not a final send.", "Protect client privacy — check tool policies."],
          mistakes: ["Sending AI text unedited.", "Pasting confidential data into unapproved tools."],
          quiz: [
            { q: "The right way to use AI for client emails is to:", options: ["Send its output directly", "Use it as a first draft you review and edit", "Never use it", "Let the client edit it"], answer: "Use it as a first draft you review and edit", explanation: "AI drafts; you verify and finalise." },
            { q: "It's fine to paste any client data into any AI tool.", options: ["True", "False"], answer: "False", explanation: "Only use tools the client approves and respect privacy." },
          ],
        },
      ],
    },
    {
      title: "Working With Clients",
      chapters: [
        {
          title: "Onboarding a new client",
          summary: "A smooth onboarding sets expectations and prevents problems later.",
          concepts: [
            "Collect goals, tools, logins (securely), working hours, and priorities.",
            "Agree scope, rate, and how you'll communicate before starting.",
            "Create a shared 'client hub' doc with everything in one place.",
            "Start with a small task to build trust.",
          ],
          steps: [
            "Send an onboarding questionnaire.",
            "Set up secure access (password manager, shared drive).",
            "Document the client's preferences and SOPs.",
            "Agree the first week's priorities.",
          ],
          tips: ["Get access via a password manager, never plain text.", "Write down preferences so you don't re-ask."],
          mistakes: ["Starting with no clear scope.", "Collecting logins insecurely."],
          quiz: [
            { q: "A good first task with a new client is:", options: ["A huge complex project", "A small task that builds trust", "Nothing", "Their banking"], answer: "A small task that builds trust", explanation: "Small early wins build confidence." },
            { q: "Client logins should be shared through a password manager, not plain email.", options: ["True", "False"], answer: "True", explanation: "Secure sharing protects the client." },
          ],
        },
        {
          title: "Communication and updates",
          summary: "Regular, concise updates keep clients confident and reduce check-ins.",
          concepts: [
            "Send proactive updates; don't wait to be asked.",
            "Use a simple format: Done / Doing / Blocked.",
            "Ask clear questions with options, not open-ended ones.",
            "Match the client's preferred channel and tone.",
          ],
          steps: [
            "Send an end-of-day or weekly summary.",
            "Flag blockers early with a suggested solution.",
            "Ask questions as 'A or B?' to speed decisions.",
            "Keep tone professional and warm.",
          ],
          tips: ["Lead updates with what's done.", "Bundle questions to avoid pinging all day."],
          mistakes: ["Only messaging when there's a problem.", "Vague, open questions that stall decisions."],
          quiz: [
            { q: "A strong update format is:", options: ["A long essay", "Done / Doing / Blocked", "Just emojis", "Nothing"], answer: "Done / Doing / Blocked", explanation: "It's scannable and clear." },
            { q: "Asking 'Do you prefer A or B?' speeds up client decisions.", options: ["True", "False"], answer: "True", explanation: "Options are easier to answer than open questions." },
          ],
        },
        {
          title: "Time tracking, invoicing and getting paid",
          summary: "Track time honestly, invoice clearly, and agree payment terms upfront.",
          concepts: [
            "Track hours with a tool (Toggl, Clockify) per task.",
            "Invoice with date, items, hours, rate, total, and due date.",
            "Agree terms (e.g. weekly, 50% upfront for projects) before work.",
            "Use a clear method to receive money (Wise, PayPal, bank).",
          ],
          steps: [
            "Start a timer per task; categorise it.",
            "Summarise hours at the end of the week.",
            "Send a clear invoice with a due date.",
            "Follow up politely if payment is late.",
          ],
          tips: ["Round honestly and note what each block covered.", "Agree late-payment terms upfront."],
          mistakes: ["Vague invoices with no breakdown.", "No agreed payment terms."],
          quiz: [
            { q: "A clear invoice should always include:", options: ["Only a total", "Items, hours, rate, total and due date", "A logo only", "Nothing"], answer: "Items, hours, rate, total and due date", explanation: "Detail prevents disputes and delays." },
            { q: "Payment terms should be agreed before the work starts.", options: ["True", "False"], answer: "True", explanation: "Upfront terms avoid payment problems." },
            { q: "A common tool to track work hours is ____.", answer: "Toggl", explanation: "Toggl/Clockify track time." },
          ],
        },
        {
          title: "Handling problems and feedback",
          summary: "How you handle mistakes and feedback decides whether clients stay.",
          concepts: [
            "Own mistakes quickly, propose a fix, and prevent a repeat.",
            "Don't be defensive about feedback — treat it as data.",
            "Set boundaries kindly when scope creeps.",
            "If a client is a bad fit, end professionally.",
          ],
          steps: [
            "Acknowledge the issue and apologise briefly.",
            "Offer a concrete fix and timeline.",
            "Add a step to your SOP to prevent recurrence.",
            "Review feedback for patterns to improve.",
          ],
          example: "A VA misses a deadline, immediately messages: 'I missed this — it'll be done by 2pm and I've added a calendar reminder so it won't happen again.' The client stays.",
          tips: ["Fix-forward beats excuses.", "Document the lesson so it never repeats."],
          mistakes: ["Hiding or excusing mistakes.", "Letting scope creep without a word."],
          quiz: [
            { q: "When you make a mistake with a client, you should:", options: ["Hide it", "Own it and propose a fix", "Blame the tool", "Quit"], answer: "Own it and propose a fix", explanation: "Accountability builds trust." },
            { q: "Feedback should be treated as useful data, not a personal attack.", options: ["True", "False"], answer: "True", explanation: "Feedback helps you improve." },
          ],
        },
      ],
    },
    {
      title: "Getting Hired & Growing",
      chapters: [
        {
          title: "Building a portfolio that wins clients",
          summary: "Even with no clients, you can show skills with samples and a clear profile.",
          concepts: [
            "Create sample work: a mock inbox cleanup, a research table, an SOP.",
            "A one-page profile: who you help, what you do, results, and a photo.",
            "Testimonials (even from practice clients) build trust fast.",
            "Show, don't just tell — link to real examples.",
          ],
          steps: [
            "Make 3 strong samples that match your niche.",
            "Write a clear profile headline and summary.",
            "Collect 1–2 testimonials.",
            "Put it all on a simple page or Google Doc/PDF.",
          ],
          tips: ["Tailor samples to the niche you want.", "Lead your profile with the client's benefit."],
          mistakes: ["A profile listing tasks, not outcomes.", "No work samples at all."],
          quiz: [
            { q: "With no paid clients yet, the best way to prove skill is:", options: ["Say 'trust me'", "Show sample work and testimonials", "Lower your rate to $1", "Wait"], answer: "Show sample work and testimonials", explanation: "Proof beats claims." },
            { q: "A VA profile should lead with the client's benefit, not a task list.", options: ["True", "False"], answer: "True", explanation: "Benefits sell; task lists don't." },
          ],
        },
        {
          title: "Where to find VA jobs",
          summary: "Combine job boards, freelance platforms, and direct outreach.",
          concepts: [
            "Platforms: Upwork, OnlineJobs.ph, Fiverr, Belay, Time Etc.",
            "Direct outreach: DM founders and offer specific help.",
            "Referrals from happy clients are the best source.",
            "Apply daily and follow up — volume matters early.",
          ],
          steps: [
            "Create strong profiles on 1–2 platforms.",
            "Apply to 5 relevant jobs daily with tailored notes.",
            "Send 3 direct outreach messages daily.",
            "Ask every happy client for a referral.",
          ],
          tips: ["Personalise every application.", "Track your applications and replies."],
          mistakes: ["Copy-paste applications.", "Relying on one platform only."],
          quiz: [
            { q: "The strongest long-term source of VA work is:", options: ["Cold ads", "Referrals from happy clients", "Random luck", "Spam"], answer: "Referrals from happy clients", explanation: "Referrals convert best." },
            { q: "Personalising each application improves your hire rate.", options: ["True", "False"], answer: "True", explanation: "Tailored applications stand out." },
          ],
        },
        {
          title: "Writing proposals that get replies",
          summary: "A great proposal is short, specific, and about the client — not you.",
          concepts: [
            "Open by showing you read their post and understand the problem.",
            "Give a mini-plan: how you'd handle their exact need.",
            "Show one relevant proof point.",
            "End with a clear, low-friction next step.",
          ],
          steps: [
            "Restate their problem in one line.",
            "Outline 2–3 steps you'd take.",
            "Add one relevant sample or result.",
            "Propose a quick call or trial task.",
          ],
          example: "'You mentioned your inbox eats 2 hours a day. I'd set up filters + templates and run daily triage. I did this for a coach and cut her inbox time 70%. Open to a 15-min call this week?'",
          tips: ["Lead with them, not 'I'.", "Keep it under 150 words."],
          mistakes: ["Generic templates.", "All about you, not the client."],
          quiz: [
            { q: "A winning proposal focuses mostly on:", options: ["Your life story", "The client's specific problem and your plan", "Your rate only", "Emojis"], answer: "The client's specific problem and your plan", explanation: "Client-centred proposals win." },
            { q: "Shorter, specific proposals usually beat long generic ones.", options: ["True", "False"], answer: "True", explanation: "Specific and concise stands out." },
          ],
        },
        {
          title: "Interviews, rates and growing your income",
          summary: "Interview with confidence, price by value, and raise rates as you prove results.",
          concepts: [
            "Prepare examples of problems you've solved.",
            "Ask the client about their goals and biggest time-drains.",
            "Move from hourly to packages/retainers for stable income.",
            "Raise rates as your skills and results grow.",
          ],
          steps: [
            "Prepare 3 STAR stories (Situation, Task, Action, Result).",
            "Ask 2 smart questions about their needs.",
            "Offer a retainer package once trust is built.",
            "Review rates every few months.",
          ],
          tips: ["Show outcomes, not just tasks, to justify rates.", "Retainers beat one-off hours for stability."],
          mistakes: ["Competing only on being cheapest.", "Never raising your rate."],
          quiz: [
            { q: "For stable income, a VA should aim to move toward:", options: ["One-off cheap tasks", "Retainers/packages with steady clients", "No clients", "Lower rates"], answer: "Retainers/packages with steady clients", explanation: "Retainers give predictable income." },
            { q: "A good interview answer uses real examples of results you delivered.", options: ["True", "False"], answer: "True", explanation: "Evidence builds confidence." },
            { q: "A structured interview-answer format is ____ (Situation, Task, Action, Result).", answer: "STAR", explanation: "STAR keeps answers concrete." },
          ],
        },
      ],
    },
  ],
};
