// Initial course categories from the product spec (Kenya/Qatar/Africa/global remote).
export const COURSE_CATEGORIES = [
  "Virtual Assistant",
  "AI Prompt Engineering",
  "ChatGPT for Work",
  "Data Entry",
  "Social Media Management",
  "Customer Support",
  "Email Management",
  "Calendar Management",
  "Canva Design",
  "Content Writing",
  "Copywriting",
  "Digital Marketing",
  "SEO",
  "WordPress",
  "Basic Web Development",
  "Frontend Development",
  "React",
  "JavaScript",
  "Python Fundamentals",
  "Excel for Remote Work",
  "Google Sheets",
  "Google Docs",
  "Notion",
  "Transcription",
  "Lead Generation",
  "LinkedIn Optimization",
  "Freelancing",
  "Upwork Success",
  "Fiverr Success",
  "Remote Job Interview Skills",
  "AI Tools for Productivity",
  "Automation with AI",
  "CRM Basics",
  "Project Management",
  "Customer Success",
  "Bookkeeping Basics",
  "YouTube Automation",
  "Affiliate Marketing",
] as const;

export const TARGET_MARKETS = ["Kenya", "Qatar", "Africa", "Global Remote"] as const;

export const COUNTRIES = [
  { name: "Kenya", flag: "🇰🇪" },
  { name: "Qatar", flag: "🇶🇦" },
  { name: "United Arab Emirates", flag: "🇦🇪" },
  { name: "Saudi Arabia", flag: "🇸🇦" },
  { name: "Nigeria", flag: "🇳🇬" },
  { name: "South Africa", flag: "🇿🇦" },
  { name: "Remote / Global", flag: "🌍" },
] as const;
