-- ============================================================================
-- 019_certification_seed.sql  —  ~40 sample published questions
-- Idempotent (guarded by the 'seed' tag). Lets the certification flow be tested
-- end-to-end before the admin fills the real 500-question bank. Safe to delete
-- later: `delete from certification_questions where tags @> array['seed'];`
-- ============================================================================

do $$
declare v_quiz uuid := 'c0000000-0000-4000-8000-000000000001';
begin
  if not exists (select 1 from public.certification_questions where quiz_id = v_quiz and tags @> array['seed']) then
    insert into public.certification_questions
      (quiz_id, type, prompt, options, correct_answer, explanation, difficulty, course_category, topic, tags, status, source, ai_reviewed)
    values
    (v_quiz,'multiple_choice','What does "LLM" stand for in the context of AI?','["Large Language Model","Linear Learning Machine","Logical Language Method","Long Latency Memory"]','Large Language Model','LLMs like GPT are trained on large text corpora to predict language.','beginner','AI Fundamentals','LLM Basics',array['seed'],'published','manual',true),
    (v_quiz,'true_false','Generative AI can produce new content such as text and images.','["True","False"]','True','Generative models create novel outputs rather than only classifying.','beginner','AI Fundamentals','Generative AI',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','Which best describes a "token" for a language model?','["A chunk of text (word or sub-word)","A security password","A type of GPU","A database row"]','A chunk of text (word or sub-word)','Models process text as tokens, often sub-word units.','beginner','AI Fundamentals','Tokens',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','What is a "hallucination" in an AI model?','["Confident but incorrect output","A hardware failure","A training dataset","An encryption method"]','Confident but incorrect output','Hallucinations are plausible-sounding but false statements.','intermediate','AI Fundamentals','Reliability',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','Which factor most improves an AI prompt''s output quality?','["Clear, specific instructions and context","Using ALL CAPS","Adding many emojis","Making it as short as possible"]','Clear, specific instructions and context','Specificity and context reduce ambiguity.','beginner','Prompt Engineering','Prompt Clarity',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','"Few-shot prompting" means:','["Providing example inputs/outputs in the prompt","Asking only one short question","Limiting the model to few words","Disabling the model memory"]','Providing example inputs/outputs in the prompt','Examples steer the model toward the desired format.','intermediate','Prompt Engineering','Few-shot',array['seed'],'published','manual',true),
    (v_quiz,'true_false','Giving the AI a role (e.g. "act as a recruiter") can improve responses.','["True","False"]','True','Role framing sets tone, vocabulary, and perspective.','beginner','Prompt Engineering','Role Prompting',array['seed'],'published','manual',true),
    (v_quiz,'scenario','A client wants a product description but the AI output is too generic. What is the best next step?','["Add target audience, tone, and key features to the prompt","Resend the same prompt repeatedly","Switch to a different language","Ask the client to write it"]','Add target audience, tone, and key features to the prompt','More context yields a tailored result.','intermediate','Prompt Engineering','Iteration',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','"Chain-of-thought" prompting encourages the model to:','["Show step-by-step reasoning","Produce shorter answers","Ignore the question","Only output code"]','Show step-by-step reasoning','Asking for steps often improves reasoning tasks.','advanced','Prompt Engineering','Chain-of-thought',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','Which is a strong practice when using AI output for a client deliverable?','["Review and fact-check before delivery","Deliver it unread","Never edit it","Hide that AI was used if asked directly"]','Review and fact-check before delivery','You are responsible for accuracy and quality.','beginner','Prompt Engineering','Quality Control',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','A key benefit of remote work for employers is:','["Access to a wider talent pool","Higher office rent","Slower communication","Mandatory relocation"]','Access to a wider talent pool','Remote hiring removes geographic limits.','beginner','Remote Work','Fundamentals',array['seed'],'published','manual',true),
    (v_quiz,'true_false','Asynchronous communication means teammates must reply instantly.','["True","False"]','False','Async work allows responses on each person''s schedule.','beginner','Remote Work','Async Communication',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','Which tool category is used for remote team video meetings?','["Video conferencing (e.g. Zoom, Meet)","Spreadsheet software","Photo editors","Compilers"]','Video conferencing (e.g. Zoom, Meet)','Video conferencing enables face-to-face remote calls.','beginner','Remote Work','Tools',array['seed'],'published','manual',true),
    (v_quiz,'scenario','You will miss a deadline due to a blocker. The best remote-work action is:','["Proactively communicate early with status and a new ETA","Stay silent and hope no one notices","Wait until the deadline passes to explain","Blame a teammate"]','Proactively communicate early with status and a new ETA','Early, honest communication builds trust.','intermediate','Remote Work','Professionalism',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','A good practice for remote productivity is:','["Set clear working hours and boundaries","Never take breaks","Keep all notifications on always","Avoid written documentation"]','Set clear working hours and boundaries','Boundaries prevent burnout and improve focus.','beginner','Remote Work','Productivity',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','On freelance platforms, a strong profile should emphasize:','["Relevant skills, portfolio, and results","Only your hourly rate","Personal phone number","Unrelated hobbies"]','Relevant skills, portfolio, and results','Clients hire based on demonstrated value.','beginner','Freelancing','Profiles',array['seed'],'published','manual',true),
    (v_quiz,'true_false','A clear scope of work helps prevent disputes with clients.','["True","False"]','True','Defined deliverables and boundaries reduce misunderstandings.','beginner','Freelancing','Scope',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','"Scope creep" refers to:','["Work expanding beyond the agreed deliverables","A pricing discount","A type of contract","A payment method"]','Work expanding beyond the agreed deliverables','Uncontrolled additions erode time and profit.','intermediate','Freelancing','Scope',array['seed'],'published','manual',true),
    (v_quiz,'scenario','A client asks for extra work not in the contract. Best response:','["Acknowledge it and propose a change order / added fee","Do it all for free immediately","Ignore the request","End the project abruptly"]','Acknowledge it and propose a change order / added fee','Additional scope should be re-negotiated fairly.','intermediate','Freelancing','Client Management',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','A professional way to handle a negative client review is to:','["Respond calmly and offer to resolve the issue","Insult the client publicly","Delete your account","Demand it be removed with threats"]','Respond calmly and offer to resolve the issue','Composure protects your reputation.','beginner','Freelancing','Reputation',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','Which practice best protects your files from loss?','["Regular backups (e.g. cloud sync)","Storing only on one device","Emailing files to no one","Deleting drafts daily"]','Regular backups (e.g. cloud sync)','Backups guard against device failure.','beginner','Productivity Tools','Data Safety',array['seed'],'published','manual',true),
    (v_quiz,'true_false','A password manager helps you use strong, unique passwords.','["True","False"]','True','Managers generate and store unique credentials securely.','beginner','Productivity Tools','Security',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','Version control (e.g. Git) is mainly used to:','["Track and manage changes to files","Edit photos","Send invoices","Host video calls"]','Track and manage changes to files','Version control records history and enables collaboration.','intermediate','Productivity Tools','Version Control',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','Which is a good habit for managing tasks?','["Break work into prioritized, trackable tasks","Keep everything in your head","Start ten tasks at once","Avoid deadlines"]','Break work into prioritized, trackable tasks','Task breakdown improves focus and delivery.','beginner','Productivity Tools','Task Management',array['seed'],'published','manual',true),
    (v_quiz,'scenario','Your internet fails during a paid task. The most professional step is:','["Notify the client and switch to a backup connection/plan","Abandon the task","Pretend the work is done","Wait days before responding"]','Notify the client and switch to a backup connection/plan','Communication plus a contingency keeps trust.','intermediate','Remote Work','Reliability',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','When writing a client message, clarity is improved by:','["Short paragraphs and specific asks","Long unbroken text","Vague requests","No subject line"]','Short paragraphs and specific asks','Structured, specific writing is easier to act on.','beginner','Communication','Writing',array['seed'],'published','manual',true),
    (v_quiz,'true_false','Summarizing agreed next steps after a call reduces misunderstandings.','["True","False"]','True','A written recap aligns expectations.','beginner','Communication','Follow-up',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','A professional email tone is best described as:','["Polite, clear, and concise","Overly casual with slang","Aggressive and demanding","Full of jargon only"]','Polite, clear, and concise','Professional tone builds credibility.','beginner','Communication','Tone',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','Which is the best way to handle unclear client requirements?','["Ask clarifying questions before starting","Guess and hope","Deliver something unrelated","Refuse to communicate"]','Ask clarifying questions before starting','Clarification prevents wasted rework.','beginner','Communication','Requirements',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','Which pricing approach charges based on the value/outcome delivered?','["Value-based pricing","Random pricing","Free work","Hourly only"]','Value-based pricing','Value pricing ties fee to client outcomes.','advanced','Freelancing','Pricing',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','A "deliverable" in a project is:','["A specific tangible output you provide","A meeting invite","A client complaint","A tax form"]','A specific tangible output you provide','Deliverables are the concrete results agreed upon.','beginner','Freelancing','Scope',array['seed'],'published','manual',true),
    (v_quiz,'true_false','Sharing a client''s confidential data publicly is acceptable if it helps your portfolio.','["True","False"]','False','Confidentiality must be respected; get permission first.','beginner','Freelancing','Ethics',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','Which best reduces AI output bias in a deliverable?','["Review, verify, and edit for fairness and accuracy","Trust it blindly","Only use the first draft","Remove all context"]','Review, verify, and edit for fairness and accuracy','Human review mitigates model bias.','advanced','AI Fundamentals','Ethics',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','Which is an example of a good measurable goal?','["Publish 3 blog posts this week","Do better","Work harder","Be productive"]','Publish 3 blog posts this week','Specific, measurable goals drive progress.','beginner','Productivity Tools','Goal Setting',array['seed'],'published','manual',true),
    (v_quiz,'scenario','A recruiter asks for your availability across time zones. Best reply:','["State your hours in a shared reference (e.g. UTC) and overlap","Say ''anytime'' with no detail","Refuse to answer","Only give your local time with no zone"]','State your hours in a shared reference (e.g. UTC) and overlap','Time-zone clarity avoids scheduling errors.','intermediate','Remote Work','Time Zones',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','Two-factor authentication (2FA) improves account security by:','["Requiring a second verification step","Making passwords optional","Sharing your password","Disabling login"]','Requiring a second verification step','2FA adds a layer beyond the password.','beginner','Productivity Tools','Security',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','A portfolio is most persuasive when it shows:','["Real results and before/after outcomes","Only a list of tools","No examples","Unrelated personal photos"]','Real results and before/after outcomes','Evidence of impact wins clients.','intermediate','Freelancing','Portfolio',array['seed'],'published','manual',true),
    (v_quiz,'true_false','Proofreading AI-generated text before sending is a good professional habit.','["True","False"]','True','Editing ensures quality and catches errors.','beginner','Prompt Engineering','Quality Control',array['seed'],'published','manual',true),
    (v_quiz,'multiple_choice','Which is the safest way to receive freelance payments?','["Through the platform''s secure payment system","Cash mailed by post","Sharing full bank login","Gift cards from strangers"]','Through the platform''s secure payment system','Platform escrow/payment protects both parties.','beginner','Freelancing','Payments',array['seed'],'published','manual',true),
    (v_quiz,'scenario','You finished a task early and found a small improvement. Best move:','["Mention the optional improvement to the client","Silently change scope","Charge extra without telling them","Do nothing and hide it"]','Mention the optional improvement to the client','Transparency plus initiative delights clients.','intermediate','Communication','Client Management',array['seed'],'published','manual',true);
  end if;
end $$;
